export const GET_RESTAURANTS_ORDER_REQUEST = "GET_RESTAURANTS_ORDER_REQUEST"
export const GET_RESTAURANTS_ORDER_SUCCESS = "GET_RESTAURANTS_ORDER_SUCCESS"
export const GET_RESTAURANTS_ORDER_FAILURE = "GET_RESTAURANTS_ORDER_FAILURE"

// Restaurant Order/ ActionTypes.js
export const UPDATE_ORDER_STATUS_REQUEST = "UPDATE_ORDER_STATUS_REQUEST"
export const UPDATE_ORDER_STATUS_SUCCESS = "UPDATE_ORDER_STATUS_SUCCESS"
export const UPDATE_ORDER_STATUS_FAILURE = "UPDATE_ORDER_STATUS_FAILURE"

export const UPDATE_PAYMENT_STATUS_REQUEST = "UPDATE_PAYMENT_STATUS_REQUEST"
export const UPDATE_PAYMENT_STATUS_SUCCESS = "UPDATE_PAYMENT_STATUS_SUCCESS"
export const UPDATE_PAYMENT_STATUS_FAILURE = "UPDATE_PAYMENT_STATUS_FAILURE"

export const SEARCH_ORDER_REQUEST = "SEARCH_ORDER_REQUEST";
export const SEARCH_ORDER_SUCCESS = "SEARCH_ORDER_SUCCESS";
export const SEARCH_ORDER_FAILURE = "SEARCH_ORDER_FAILURE";