export const CREATE_RESTAURANT_ORDER_REQUEST = "CREATE_RESTAURANT_ORDER_REQUEST"
export const CREATE_RESTAURANT_ORDER_SUCCESS = "CREATE_RESTAURANT_ORDER_SUCCESS"
export const CREATE_RESTAURANT_ORDER_FAILURE = "CREATE_RESTAURANT_ORDER_FAILURE"

// Restaurant Order/ ActionTypes.js
export const UPDATE_ORDER_STATUS_REQUEST = "UPDATE_ORDER_STATUS_REQUEST"
export const UPDATE_ORDER_STATUS_SUCCESS = "UPDATE_ORDER_STATUS_SUCCESS"
export const UPDATE_ORDER_STATUS_FAILURE = "UPDATE_ORDER_STATUS_FAILURE"
